export const Products = [
    {
        id:1,
        category:"Apple",
        title:"Apple Watch Series 9 [GPS 45mm]",
        imgSrc:"https://m.media-amazon.com/images/I/71OSc6IfGcL._AC_SL1500_.jpg",
        amazonLink:"https://amzn.to/3PuckZp",
        description:"Apple Smart Watch",
        price:99999,
    },
    {
        id:2,
        category:"Apple",
        title:"Apple Watch SE (2nd Gen) [GPS 40mm]",
        imgSrc:"https://m.media-amazon.com/images/I/61wjDV8p6PL._AC_SL1500_.jpg",
        amazonLink:"https://amzn.to/3PuckZp",
        description:"Apple Smart Watch",
        price:94999,
    },
    {
        id:3,
        category:"Apple",
        title:"Apple Watch Ultra 2 [GPS + Cellular 49mm]",
        imgSrc:"https://m.media-amazon.com/images/I/81k6R2uh1JL._AC_SX466_.jpg",
        amazonLink:"https://amzn.to/3PuckZp",
        description:"Apple Smart Watch",
        price:69999,
    },
    {
        id:4,
        category:"Apple",
        title:"Apple Watch Series 9 [GPS 45mm]",
        imgSrc:"https://m.media-amazon.com/images/I/71OSc6IfGcL._AC_SL1500_.jpg",
        amazonLink:"https://amzn.to/3PuckZp",
        description:"Apple Smart Watch",
        price:99999,
    },
    {
        id:5,
        category:"Apple",
        title:"Apple Watch SE (2nd Gen) [GPS 40mm]",
        imgSrc:"https://m.media-amazon.com/images/I/61wjDV8p6PL._AC_SL1500_.jpg",
        amazonLink:"https://amzn.to/3PuckZp",
        description:"Apple Smart Watch",
        price:94999,
    },
    {
        id:4,
        category:"SAMSUNG",
        title:"SAMSUNG Galaxy Watch FE 40mm",
        imgSrc:"https://m.media-amazon.com/images/I/71EHTkDQqfL._AC_SX569_.jpg",
        amazonLink:"https://amzn.to/3PuckZp",
        description:"SAMSUNG Smart Watch",
        price:54999,
    },
    {
        id:5,
        category:"SAMSUNG",
        title:"SAMSUNG Galaxy Watch 4 40mm",
        imgSrc:"https://m.media-amazon.com/images/I/61em2RBifsL.__AC_SY300_SX300_QL70_FMwebp_.jpg",
        amazonLink:"https://amzn.to/3PuckZp",
        description:"SAMSUNG Smart Watch",
        price:58999,
    },
    {
        id:6,
        category:"Apple",
        title:"Apple Watch SE (2nd Gen) [GPS 40mm]",
        imgSrc:"https://m.media-amazon.com/images/I/61wjDV8p6PL._AC_SL1500_.jpg",
        amazonLink:"https://amzn.to/3PuckZp",
        description:"Apple Smart Watch",
        price:94999,
    },
    {
        id:7,
        category:"SAMSUNG",
        title:"SAMSUNG Galaxy Watch 5 44mm",
        imgSrc:"https://m.media-amazon.com/images/I/61s1Na3W61L._AC_SX679_.jpg",
        amazonLink:"https://amzn.to/3PuckZp",
        description:"SAMSUNG Smart Watch",
        price:54999,
    },
    {
        id:8,
        category:"SAMSUNG",
        title:"SAMSUNG Galaxy Watch 4 40mm",
        imgSrc:"https://m.media-amazon.com/images/I/61em2RBifsL.__AC_SY300_SX300_QL70_FMwebp_.jpg",
        amazonLink:"https://amzn.to/3PuckZp",
        description:"SAMSUNG Smart Watch",
        price:58999,
    },
    {
        id:9,
        category:"SAMSUNG",
        title:"SAMSUNG Galaxy Watch 5 44mm",
        imgSrc:"https://m.media-amazon.com/images/I/61s1Na3W61L._AC_SX679_.jpg",
        amazonLink:"https://amzn.to/3PuckZp",
        description:"SAMSUNG Smart Watch",
        price:54999,
    },
    {
        id:10,
        category:"SAMSUNG",
        title:"SAMSUNG Galaxy Watch FE 40mm",
        imgSrc:"https://m.media-amazon.com/images/I/71EHTkDQqfL._AC_SX569_.jpg",
        amazonLink:"https://amzn.to/3PuckZp",
        description:"SAMSUNG Smart Watch",
        price:54999,
    },
    {
        id:11,
        category:"huawei",
        title:"Amazfit  Watch 6 Classic 47mm",
        imgSrc:"https://m.media-amazon.com/images/I/61IBMgqxJWL._AC_SX425_.jpg",
        amazonLink:"https://amzn.to/3PuckZp",
        description:"huawei Smart Watch",
        price:65999,
    },
    {
        id:12,
        category:"huawei",
        title:"AmazfitWatch 4 Classic 42mm",
        imgSrc:"https://m.media-amazon.com/images/I/61ocbwnK2BL._AC_SX522_.jpg",
        amazonLink:"https://amzn.to/3PuckZp",
        description:"huawei Smart Watch",
        price:79999,
    },
    {
        id:13,
        category:"huawei",
        title:"Amazfit Active Smart Watch 42mm",
        imgSrc:"https://m.media-amazon.com/images/I/71cKQf0WBzL._AC_SX679_.jpg",
        amazonLink:"https://amzn.to/3PuckZp",
        description:"huawei Smart Watch",
        price:89999,
    },
    {
        id:14,
        category:"huawei",
        title:"Amazfit Watch 4 Classic 42mm",
        imgSrc:"https://m.media-amazon.com/images/I/61ocbwnK2BL._AC_SX522_.jpg",
        amazonLink:"https://amzn.to/3PuckZp",
        description:"huawei Smart Watch",
        price:79999,
    },
    {
        id:15,
        category:"huawei",
        title:"Amazfit Active Smart Watch 42mm",
        imgSrc:"https://m.media-amazon.com/images/I/71cKQf0WBzL._AC_SX679_.jpg",
        amazonLink:"https://amzn.to/3PuckZp",
        description:"huawei Smart Watch",
        price:89999,
    },
    {
        id:16,
        category:"huawei",
        title:"Amazfit Watch 6 Classic 47mm",
        imgSrc:"https://m.media-amazon.com/images/I/61IBMgqxJWL._AC_SX425_.jpg",
        amazonLink:"https://amzn.to/3PuckZp",
        description:"huawei Smart Watch",
        price:65999,
    },
    
]

// /* <button className='btn btn-warning'>CartItems Total Price = {totalPrice}{" "}</button> 